chunk-loading-advanced:
  auto-config-send-distance: true
  player-max-concurrent-loads: 4.0
  player-max-chunk-load-rate: 100.0

chunk-loading-basic:
  player-max-chunk-load-rate: 100.0

async-chunks:
  threads: 3

packet-limiter:
  kick-message: '&cSent too many packets'
  limits:
    all:
      interval: 7.0
      max-packet-rate: 500.0
    PacketPlayInAutoRecipe:
      interval: 4.0
      max-packet-rate: 5.0
      action: DROP

unsupported-settings:
  allow-permanent-block-break-exploits: false
  allow-piston-duplication: false
